[package]
name = "launcher-schizophrenia"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = "MIT"
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
tauri = { version = "1.2", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
simple_logger = "4.1"
color-eyre = "0.6"
sysinfo = "0.28"
bytesize = "1"
reqwest = "0.11"
chksum = { version = "0.1.0-rc5", default-features = false, features = ["sha2_256"] }
anyhow = "1"
dirs = "5"
tempfile = "3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = 'fat'
codegen-units = 1
strip = true
panic = "abort"
